AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for creating security group  
Resources:
  DemoSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: A Security Group for Demo-EC2
      GroupName:  SG_ssh_https
      VpcId: vpc-09b77ec6cfd8f4129
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
           - Value: SG1_SSH_HTTPS
             Key: Name